apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '${repo_url}'
    targetRevision: '${target_revision}'
    path: projects/platform-services
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
